src/app.py
from flask import Flask, render_template, session
from src.common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "123"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.html')


from src.models.users.views import user_blueprint
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import store_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")
app.register_blueprint(store_blueprint, url_prefix="/stores")

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, url_for, redirect


from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST' :
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price() # This function already saves the alert to MongoDB

        return redirect(url_for('users.user_alerts'))
    return render_template('alerts/create_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form['price'])

        alert.price_limit=price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))
    return render_template('/alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/items/views.py
from flask import Blueprint


item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass

src/models/stores/views.py
from flask import Blueprint, render_template, request, json, redirect, url_for
import src.models.users.decorators as user_decorators
from src.models.stores.store import Store

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores =Store.all()
    return render_template('stores/store_index.html', stores= stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('/stores/store.html', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['store_query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name=tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))
    return render_template('stores/edit_store.html', store=store )


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['store_query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('/stores/create_store.html')

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

import src.models.users.errors as UserErrors
from src.models.users.user import User
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
@user_decorators.already_logged_in
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.html")    # send the user an error if the login is invalid


@user_blueprint.route('/register', methods=['GET', 'POST'])
@user_decorators.already_logged_in
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.html")    # send the user an error if the login is invalid


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts =user.get_alerts()
    return render_template('/users/alerts.html', alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))

src/templates/alerts/alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Alert
        {% if alert.active %}
            <small>for '{{alert.item.name}}'</small>
        {% else %}
            <small>for '{{alert.item.name}}' (Deactivated)</small>
        {% endif %}
    </h1>
</div>
<p>Last price found was <strong>{{ alert.item.price }}</strong></p>
<p>Last checked on <strong> {{alert.last_checked.strftime('%d-%m-%Y at %H:%M') }}</strong></p>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="btn-group" role="group">
            <a class="btn btn-primary" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}"
               role="button">Check Item Price Now</a>
            <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit Store</a>
            <div class="btn-group" role="group">
                <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit
                    Alert</a>
                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    {% if alert.active %}
                        <li><a href="{{ url_for('alerts.deactivate_alert', alert_id = alert._id) }}">Deactivate Alert</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li class="disabled"><a href="#">Delete Alert</a></li>
                    {% else %}
                        <li><a href="{{ url_for('alerts.activate_alert', alert_id = alert._id) }}">Activate Alert</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('alerts.delete_alert', alert_id= alert._id) }}">Delete Alert</a></li>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/alerts/create_alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert </h1>
    </div>
    <div class="size">
        <form  method="post">
            <div class="form-group">
                <label for="name">Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price">Desired Price ($)</label>
                <input type="text" class="form-control" id="price" name="price" placeholder="$$$" aria-describedby="pricelimitblock">
                <p id="pricelimitblock" class="help-block">We will send you an e-mail when the price of this item reaches or is below this value.</p>
            </div>
            <button type="submit" class="btn btn-default">Create Alert</button>
        </form>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Alert </h1>
    </div>
    <div class="size">
        <form  method="post">
            <div class="form-group">
                <label for="name">Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name" disabled>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://..." disabled>
            </div>
            <div class="form-group">
                <label for="price">Desired Price ($)</label>
                <input type="text" class="form-control" id="price" name="price" placeholder="$$$" value="{{ alert.price_limit }} " aria-describedby="pricelimitblock">
                <p id="pricelimitblock" class="help-block">We will send you an e-mail when the price of this item reaches or is below this value.</p>
            </div>
            <button type="submit" class="btn btn-default">Save Edit</button>
        </form>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>price.me</title>

    {% include 'html_dependencies.html' %}

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
      </button>
            <a class="navbar-brand" href="/"  title="Home" > price.me</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('stores.index') }}">Stores</a> </li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-bell "></span> Your Alerts</a> </li>
                    <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span>   Log Out</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in glyphicon "></span> Log In</a> </li>
                    <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-user"></span>   Sign Up</a></li>
                </ul>
            {% endif %}

        </div>

    </div>
</nav>

<div class="content container">
{% block content %}

{% endblock%}
</div>

</body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1>price.me!</h1>
    <p>We let you know when a product you want is at the price YOU want it to be!</p>
    {% if session['email'] %}
        <p>Check your alerts now!</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for( 'users.user_alerts') }}" role="button">Your Alerts!</a></p>
    {% else %}
        <p>Sign Up today using the button below!</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for( 'users.register_user') }}" role="button">Sign Up!</a></p>
    {% endif %}
</div>
{% endblock %}

src/templates/html_dependencies.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

src/templates/stores/create_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do all item URLs from this store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">HTML Tag</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tag_nameHelp">
                <span id="tag_nameHelp" class="help-block">What is the HTML tag of the item that contains the price? (Usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="store_query">Search Query</label>
                <input type="text" class="form-control" id="store_query" name="store_query" placeholder='{"id":"pricenow"}' aria-describedby="store_queryHelp">
                <span id="store_queryHelp" class="help-block">What JSON query would we have to do to find the specific tag with the price? (Remember to use double quotation marks!)</span>
            </div>
            <button type="submit" class="btn btn-default">Create Store</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Store</h1>
    </div>
    <div class="size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ store.name }}">
            </div>
            <div class="form-group">
                <label for="url_prefix">URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." value="{{ store.url_prefix }}" aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do all item URLs from this store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">HTML Tag</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="tag_nameHelp">
                <span id="tag_nameHelp" class="help-block">What is the HTML tag of the item that contains the price? (Usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="store_query">Search Query</label>
                <input type="text" class="form-control" id="store_query" name="store_query" placeholder='{"id":"pricenow"}' value='{{ store.query | tojson }}' aria-describedby="store_queryHelp">
                <span id="store_queryHelp" class="help-block">What JSON query would we have to do to find the specific tag with the price? (Remember to use double quotation marks!)</span>
            </div>
            <button type="submit" class="btn btn-warning">Save Edit</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Store
        <small>{{ store.name }}</small>
    </h1>
</div>
<p>All URLs from this store should start with <strong>{{ store.url_prefix }}</strong></p>
{% if session['email'] in config.ADMINS %}
<div class="panel panel-default">
    <div class="panel-body btn-group">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
            Store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete
            Store</a>
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/stores/store_index.html
{% extends "base.html" %}
{% block content %}
   <div class="page-header">
       <h1>Stores <small>list of supported stores</small></h1>
   </div>
    <div class="list-group">
        {%for store in stores %}
             <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
             <h4 class= "list-group-item-title">{{ store.name }}</h4>
             <p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong> </p></a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
    <a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
        <span class="glyphicon glyphicon-plus"></span> Add More
    </a>
    {% endif %}
{% endblock %}

src/templates/stores/store_list.html
{% extends "base.html" %}
{% block content %}
    <p>Nothing here yet!</p>
{% endblock %}

src/templates/users/alerts.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Alerts <small>that you have created</small></h1>
    </div>
    <div class="list-group">
        {% for alert in alerts %}
            <a href="{{ url_for ('alerts.get_alert_page', alert_id=alert._id ) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else ''}}">
                <h4 class="list-group-item-heading">
                    {% if not alert.active %} <span class="glyphicon glyphicon-remove-circle"></span> {% endif %} Alert for {{ alert.item.name }}</h4>
                <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
                Last checked on <strong> {{ alert.last_checked.strftime("%d-%m-%Y at %H:%M")  }}</strong></p>
            </a>
        {% endfor %}
    </div>
<a class="btn btn-success" href="{{ url_for('alerts.create_alert' )}}"><span class="glyphicon glyphicon-plus"></span> Add More</a>
{% endblock %}

src/templates/users/already_logged_in_page.html
{% extends "base.html" %}
{% block content %}
    <div class="size">
        <div class="alert alert-danger" role="alert">You are already logged in.</div>
    </div>
{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
    <div class="size">
        <form action="{{ url_for('users.login_user') }}" method="post">
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-info">Log In</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div class="size">
        <form  action="{{ url_for('users.register_user') }}" method="post">
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-success">Sign Up!</button>
                </form>
    </div>
{% endblock %}

src/templates/users/requires_admin_page.html
{% extends "base.html" %}
{% block content %}
    <div class="size">
        <div class="alert alert-danger" role="alert">You need to be an administrator in order to do that.</div>
    </div>
{% endblock %}

src/templates/users/requires_login_page.html
{% extends "base.html" %}
{% block content %}
    <div class="size">
        <form action="{{ url_for('users.login_user') }}" method="post">
                <div class="alert alert-danger" role="alert">You need to be logged in in order to do that.</div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-info">Log In</button>
        </form>
    </div>
{% endblock %}